[Service]
  Port = 49952
  ConnectRetries = 3
  HealthCheck = ""
  Labels = [ "opc-ua" ]
  StartupMsg = "The opc-ua device service has started"
  ReadMaxLimit = 256
  Timeout = 5000

[Clients]
  [Clients.Data]
    Host = 'edgex-core-data'
    Port = 48080

  [Clients.Metadata]
    Host = 'edgex-core-metadata'
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"

[[DeviceList]]
#  Name = "ICT SmartLab OPC-UA Server"
  Name = "opcuaServer"
  Profile = "Docker_ICT SmartLab OPC-UA Server - Profile"
  Description = "An OPC-UA device"
  [DeviceList.Protocols]
    [DeviceList.Protocols.OPC-UA]
      Address = "192.168.0.5"
      Port = 4840
      Path = ""
